---
title: "chapter01_简介"
output:
  html_document:
    toc: TRUE
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(prompt=TRUE,comment='',echo=TRUE,collapse=TRUE,message=FALSE,warning=FALSE)
```

# 1 ggplot2简介

## 1.1 图形的语法

- Wilkinson(2005)创建了一套用来描述所有统计图形深层特性的语法规则，该语法回答了“什么是统计图形”这一问题。Wickham (2010)提出了基于Wilkinson语法的图层图形语法，它将图层作为主要的考察对象，并使其嵌人到R中。

- 简而言之，这套语法告诉我们，一张统计图形就是从数据到几何对象 (geometric object，缩写为geom，包括点、线、条形等)的图形属性(aestheticattributes，缩写为aes，包括颜色、形状、大小等)的一个映射。此外，图形中还可能包含数据的统计变换(statistical transformation，缩写为stats)，最后绘制在某个特定的坐标系(coordinate system，缩写为coord)中，而分面(facet，指将绘图窗口划分为若干个子窗口)则可以用来生成数据不同子集的图形。总而言之，一张统计图形就是由上述这些独立的图形部件所组成的。

- 最基础的部分是你想要可视化的数据(data)以及一系列将数据中的变量对应到图形属性的映射(mapping)；

- 几何对象(geom)代表你在图中实际看到的图形元素，如点、线、多边形等；

- 统计变换(stats)是对数据进行的某种汇总。例如，将数据分组计数以创建直方图，或将一个二维的关系用线性模型进行解释。统计变换是可选的，但通常非常有用；

- 标度(scale)的作用是将数据的取值映射到图形空间，例如用颜色、大小或形状来表示不同的取值。展现标度的常见做法是绘制图例和坐标轴一它们实际上是从图形到数据的一个映射，使读者可以从图形中读取原始的数据；

- 坐标系(coord)描述了数据是如何映射到图形所在的平面的，它同时提供了看图所需的坐标轴和网格线。我们通常使用的是笛卡尔坐标系，但也可以将其变换为其他类型，如极坐标和地图投影；

- 分面(facet)描述了如何将数据分解为各个子集，以及如何对子集作图并联合进行展示。分面也叫做条件作图或网格作图。