---
title: "women-HTML"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Regression Report

```{r echo=FALSE, results='hide'}
n <- nrow(women) 
fit <- lm(weight ~ height, data=women)  
sfit <- summary(fit) 
b <- coefficients(fit) 
```

Linear regression was used to model the relationship between weights and height in a sample of `r n` women. The equation

    **weight = `r b[[1]]` +  `r b[[2]]` * height**  

accounted for `r round(sfit$r.squared,2)`% of the variance in weights. The ANOVA table is given below.

```{r echo=FALSE, results='asis'}
library(xtable) 
options(xtable.comment=FALSE)  # 语句options(xtable.comment=FALSE)省略了多余的信息。
print(xtable(sfit), type="html", html.table.attributes="border=0") 
# print()函数中的type="html"选项把xtable对象输出为一个HTML表格。默认设置中，这个表格有个无趣的1像素边界，这里通过添加html.table.attributes="border=0"将其移除。额外的格式化选项参见help(print.xtable)。
```

The regression is plotted in the following figure.

```{r echo=FALSE, fig.width=5, fig.height=4}
library(ggplot2) 
ggplot(data=women, aes(x=height, y=weight)) +       
  geom_point() + geom_smooth(method="lm")
```
